razor_3/razor_3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace razor_3.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Campus()
        {
            return View();
        }
        public ActionResult Basin()
        {
            return View();
        }
        public ActionResult Iletisim()
        {
            return View();
        }
    }
}

razor_3/razor_3/Views/Default/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="aciklama">
    <h2>Hakkımızda</h2>
</div>
<div class="vizyon">
    <div class="op">
        <img src="~/image/cevre-bilim-2.jpg" />
    </div>
    <div class="yazi">
        <p>VIZYON ve MISYONUMUZ</p>
    </div>
    @*<img class="bh" src="~/image/bayram bey png.png" />*@
    <div class="resYaz">
        <img class="vz" src="~/image/col-icon-3.png" />
        <p>
            Çevre Bilim Okulları olarak Atatürk’ün gösterdiği yolda ülkeyi çağdaş uygarlık seviyesinin üstüne çıkartacak gençleri işin ehli eğitimciler aracılığıyla çok boyutlu düşünen, yaşamı öğreten başarılı bireyler yetiştiren bir eğitim modeli oluşturmaktır.<br />
        </p>
        <img class="ms" src="~/image/col-icon-2.png" />
        <p>
            Öğrencilerimizin kişisel gelişimlerini, potansiyelini, yeteneklerini, becerilerini, algılarını sonuna kadar geliştirerek öğreten, yaşayarak öğrenmenin yanında üretmesini de sağlayan bir eğitim öğretim modeliyle “çağın insanını” yetiştirmektir.<br />
        </p>
        <img class="hf" src="~/image/col-icon-4.png" />
        <p>
            Öğrencilerimizi çok boyutlu düşünen, kendine güvenen, sorgulayan, tartışan, araştıran,, sağlıklı, mutlu, kişilikli, lider, kendisiyle ve başkalarıyla rekabet eden gençler olarak yetiştirmek bizim en asli hedefimizdir.<br />
        </p>

    </div>
</div>

razor_3/razor_3/Views/Default/Basin.cshtml
@{
    ViewBag.Title = "Basin";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<div class="aciklama">
    <h2>Basında Biz</h2>
</div>
<div class="basin">
    <p>A Haber Bültenindeyiz</p>
    <iframe width="400px" height="600px" src="https://www.youtube.com/embed/1z_dMHJJvo4?si=fDMeYQhUPJAkWzeN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> <br />
    <p>Kurucumuz Mehmet Bayram BEKTAŞ-"Dobra Dobra"programına konuk oldu</p>
    <iframe width="80%" height="600px" src="https://www.youtube.com/embed/osVGhyPGXBs?si=AhBmUqHcQF-uYTME" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <p>Kurucumuz Avrupa D ye reportaj verdi</p>
    <iframe width="80%" height="600px" src="https://www.youtube.com/embed/aAIiiRIXBMI?si=0a1UPiYFvD5yPOM0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><br />
    <p>Özel Çatalca Sınav Temel Lisesi, Mehmet Bayram Bektaş, Çatalca, Hayırlı İşler</p>
    <iframe width="80%" height="600px" src="https://www.youtube.com/embed/2lMeCa0JEvI?si=ylmbQ0NsjqiIugJ3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><br />
</div>

razor_3/razor_3/Views/Default/Campus.cshtml
@{
    ViewBag.Title = "Campus";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<div class="aciklama">
    <h2>Kampuslerimiz</h2>
</div>
<div class="campusler">
    <div class="opK">
        <img src="~/image/bilisim-atolyesi (1) (1).jpg" />
    </div>
    <div class="ilkokul">
        
        <p>

            Disiplinli bir eğitim oluşturma <br />
            Çalışma alışkanlığı kazandırma<br />
            Hedef ve amaç belirletebilme<br />
            Bireysel yetenekleri ortaya çıkarma ve geliştirme<br />
            Sosyal sorumluluk projeleri oluşturma ve katılma<br />
            Üreterek tüketmeyi öğretme<br />
            Özgüven sahibi öğrenciler yetiştirme<br />
            Sınıf dışı uygulamalı aktif öğretme<br />
            Yaşam becerilerinin geliştirme ve yaşam gerçeklerini öğretme<br />
            Kişilik gelişimini sağlama<br />
            Robotik kodlama<br />
            Akıl oyunları<br />
            1. sınıftan itibaren ana dil seviyesinde İngilizce, 2. sınıftan itibaren ana dil seviyesinde İngilizce ve Almanca iki dil öğretme<br />
            Ezberden uzak bir eğitim uygulama<br />
        </p>
        <img src="~/image/dogalyasam_1.jpeg" />
    </div>
    <div class="ortaokul">
        <img src="~/image/ortaokul_1.jpeg" />
        <p>
            Akademik başarı için sınavlara hazırlama <br />
            Uluslararası ve ulusal projelere katılma<br />
            Uluslararası öğrenci değişim projelerine katılma<br />
            Akran eğitimi uygulama<br />
            Öğrenci kulüpleri, sosyal sorumluluk projeleri<br />
            Sosyal ve kültürel çok yönlü aktiviteler gerçekleştirebilme<br />
            Bilim, zanaat ve teknolojiyi uygulamalı öğretme<br />
            Sanatsal duyarlılığı artırma ve yetenek geliştirme<br />
            Erasmus eğitim programı<br />
            Değerler eğitimi<br />
        </p>
    </div>
    <div class="lise">
        <img src="~/image/lise_1 (1).jpg" />
        <p>
            Sosyal-Kültürel çok yönlü aktiviteler gerçekleştirme <br />
            Sanatsal duyarlılığı artırma ve yetenek geliştirme<br />
            Kariyer gelişim ve kariyer planlama<br />
            Üniversite hazırlık çalışmaları (TYT - AYT hazırlık programları)<br />
            Hem okulda başarılı olma hem de sınavlara hazırlama<br />
            Akran eğitimi uygulama<br />
            Akademik başarıyı, özgüveni ve özsaygıyı geliştirme<br />
            İki yabancı dil eğitimi uygulama<br />
            Eğitimi zanaat, teknoloji, doğal yaşam, liderlik, ilgi ve yetenek yönüyle geliştirme destekleme<br />
        </p>
    </div>
</div>

razor_3/razor_3/Views/Default/Iletisim.cshtml
@{
    ViewBag.Title = "Iletisim";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<div class="opI">
    <img src="~/image/ÇBK Logo 2 (1).png" />
</div>
<div class="container">
    <div class="Iresim">
        <img src="~/image/kayit-ol-1.jpg" />
        <p>
            Bilgilerinizi Bize Bırkın Biz Sizi Arayalım
        </p>
        <table>
            <tr>
                <th>Adres: </th>
                <th><textarea rows="5" cols="48">Adresiniz:</textarea></th>
            </tr>
            <tr> </tr>
            <tr>
                <th>Ad: </th>
                <th><input type="text" name="Ad" size="50" maxlength="20" placeholder="Adınızı giriniz" required /></th>
            </tr>
            <tr> </tr>
            <tr>
                <th>Soyad: </th>
                <th><input type="text" name="soyad" size="50" maxlength="20" placeholder="Soyadınızı giriniz" required /></th>
            </tr>
            <tr> </tr>
            <tr>
                <th>Öğrenci Sınıf: </th>
                <th><input type="text" name="yas" size="50" maxlength="20" placeholder="Öğrenci sınıfı girin" required /></th>
            </tr>
            <tr> </tr>
            <tr>
                <th> Öğrenci cinsiyeti: </th>
                <th><input type="radio" name="bilgi"/>Erkek</th>
                <th><input type="radio" name="bilgi1"/>Kadın</th>
            </tr>
            <tr> </tr>
            <tr>
                <th>Yaşadıgınız ilçe: </th>
                <th>
                    <select>
                        <option>Çatalca</option>
                        <option>Büyükçekmece</option>
                        <option>Avcılar</option>
                        <option>Beylikdüzü</option>
                        <option>Tekirdag</option>
                    </select>
                </th>
            </tr>
            
            <tr>
                <th><input type="submit" class="dugme1" /></th>
                <th><input type="reset" class="dugme2" /></th>
            </tr>
            <tr> </tr>
        </table>
    </div>
</div>

razor_3/razor_3/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="slider">
    <!-- Insert to your webpage where you want to display the slider -->
    <div class="amazingslider-wrapper" id="amazingslider-wrapper-1" style="display:block;position:relative;max-width:1150px;margin:0px auto 56px;">
        <div class="amazingslider" id="amazingslider-1" style="display:block;position:relative;margin:0 auto;">
            <ul class="amazingslider-slides" style="display:none;">
                <li>
                    <img src="~/images/slider-1.png" />
                </li>
                <li>
                    <img src="~/images/Ba%C5%9Fl%C4%B1ks%C4%B1z-1_%C3%87al%C4%B1%C5%9Fma%20Y%C3%BCzeyi%201.jpg" />
                </li>
            </ul>
            <ul class="~/amazingslider-thumbnails" style="display:none;">
                <li><img src="~/images/slider-1-tn.png" /></li>
                <li><img src="~/images/Ba%C5%9Fl%C4%B1ks%C4%B1z-1_%C3%87al%C4%B1%C5%9Fma%20Y%C3%BCzeyi%201-tn.jpg" /></li>
            </ul>
        </div>
    </div>
    <!-- End of body section HTML codes -->
</div>
<div class="section">
    <div class="sec">
        <marquee>
            Kişiye özgü etkin psikolojik danışmanlık ve rehberlik uygulama. Kişiye özgü rehberlik, ilgi, yetenek ve yönlendirme takip sistemi. Öğrenme ortamını sınıfın ve okulun dışına taşıma.
        </marquee>
    </div>
    <div class="sec1">
        <img src="~/image/icon-2.png" />
        <p>Ilkokul</p>
        <p class="yaz1">
            Alanında uzman öğretmenlerle eğitme<br />
            Disiplinli bir eğitim oluşturma<br />
            Çalışma alışkanlığı kazandırma<br />
            Hedef ve amaç belirletebilme<br />
            Üreterek tüketmeyi öğretme <br />
            Özgüven sahibi öğrenciler yetiştirme <br />
        </p>
        <img class="okul1" src="~/image/ÇBK Bina yeni.png" alt="Alternate Text" />
    </div>
    <div class="sec2">
        <img src="~/image/icon-3.png" />
        <p>Ortaokul</p>
        <p class="yaz1">
            Çift yabancı dil eğitimi (Almanca ve İngilizce)<br />
            Akademik başarı için sınavlara hazırlama<br />
            Uluslararası ve ulusal projelere katılma<br />
            Uluslararası öğrenci değişim projelerine katılma <br />
            Akran eğitimi uygulama <br />
            Öğrenci kulüpleri, sosyal sorumluluk projeleri <br />
        </p>
        <img class="okul1" src="~/image/ÇBK Bina yeni.png" alt="Alternate Text" />
    </div>
    <div class="sec3">
        <img src="~/image/icon-4.png" />
        <p>Lise</p>
        <p class="yaz1">
            Sosyal-Kültürel çok yönlü aktiviteler gerçekleştirme <br />
            Sanatsal duyarlılığı artırma ve yetenek geliştirme<br />
            Kariyer gelişim ve kariyer planlama<br />
            Üniversite hazırlık çalışmaları (TYT - AYT hazırlık programları)<br />
            Hem okulda başarılı olma hem de sınavlara hazırlama<br />
            Akran eğitimi uygulama<br />
        </p>
        <img class="okul2" src="~/image/DFSD.png" alt="Alternate Text" />

    </div>
</div>

razor_3/razor_3/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>ÇBK</title>
    <link href="~/css.css" rel="stylesheet" />
    <!-- Insert to your webpage before the </head> -->
    <script src="~/sliderengine/jquery.js"></script>
    <script src="~/sliderengine/amazingslider.js"></script>
    <link rel="~/stylesheet" type="text/css" href="sliderengine/amazingslider-1.css">
    <script src="~/sliderengine/initslider-1.js"></script>
    <!-- End of head section HTML codes -->
</head>
<body>
    <div class="genel">
        <div class="ust">

            <img class="mail" src="~/image/multimedia.png" alt="Alternate Text" />
            <ul>
                <li>info@cevrebilimkoleji.com</li>
            </ul>
            <img class="tel1" src="~/image/call.png" alt="Alternate Text" />
            <ul>
                <li>0 212 789 12 20</li>
            </ul>
            <img class="tel2" src="~/image/call.png" alt="Alternate Text" />
            <ul>
                <li>0 212 795 05 60</li>
            </ul>
            <p><a href="/Default/Iletisim">Kayıt Ol</a></p>
        </div>
        <div class="header">
            <div class="logo">
                <a href="@Url.Action("Index","Default")"><img src="~/image/ÇBK Logo 2 (1).png" /></a>
            </div> <!--logo kapanış-->
            <div class="menu">
                <ul>
                    <li><a href="@Url.Action("Index","Default")"> Ana Sayfa</a></li>
                    <li><a href="@Url.Action("About","Default")"> Hakkımızda</a></li>
                    <li><a href="@Url.Action("Campus","Default")"> Kampusler</a></li>
                    <li><a href="@Url.Action("Basin","Default")"> Basında biz</a></li>
                </ul>
                <form>
                    <input type="text" name="search" class="search-box" placeholder="Arama yapın...">
                    <input type="submit" class="search-button" value="Ara">
                </form>
            </div>
        </div>
        @RenderBody()
        <div class="footer">
            <div class="sol">
                <img src="~/image/ÇBK Logo 2.png" alt="Alternate Text" />
                <p>
                    Kaleiçi Mah. Fetih Cad. <br />
                    Örnek Sok. Bina No:1 Çatalca <br />

                    0 212 789 12 20 <br />

                    info@cevrebilimkoleji.com <br />
                </p>
            </div>
            <div class="orta">

                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001.400277326747!2d28.449455875633205!3d41.21304680679166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14b54f2ce0c845d5%3A0xd987953353a33a24!2s%C3%87evre%20Bilim%20Koleji%20%C3%87atalca!5e0!3m2!1str!2str!4v1694239139668!5m2!1str!2str" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                <p>
                    Bütün Hakları Saklıdır 2023,&copy; S_BEGENJOV
                </p>
            </div>
            <div class="sag">
                <img src="~/image/ÇBK Logo 2.png" alt="Alternate Text" />
                <p>

                    Subaşı Mah. Gökçeali Cad. <br />
                    No: 259 Çatalca / İstanbul <br />

                    0 212 795 05 60 <br />

                    info@cevrebilimkoleji.com <br />
                </p>
            </div>
        </div>
    </div>
</body>
</html>